### ISSUE TITLE
Change filename

### ISSUE THREAD

**Issue by Kajalso** [im-salman/react-component-export-image#48]
All the downloads are saved as component (x).png, is it possible to change the filename before it is downloaded?

**Comment by im-salman** [comment]
Hi @Kajalso,
It is possible to change the name by passing the `fileName`  parameter.  By default it is component.

```
 exportComponent = (node, {
    fileName, 
    type, 
    html2CanvasOptions, 
    pdfOptions
})  
```

**Comment by Kajalso** [comment]
Omg, I'm blind. Thank you!

**Comment by Alex-Anev** [comment]
> Hi @Kajalso,
> It is possible to change the name by passing the `fileName` parameter. By default it is component.
> 
> ```
>  exportComponent = (node, {
>     fileName, 
>     type, 
>     html2CanvasOptions, 
>     pdfOptions
> })  
> ```

For anyone who's a little confused about this like I was. Here's what worked for me.

```
        <button onClick={
          (e) => {
            exportComponentAsPNG(
              componentRef,
              {
                fileName: "myfilename" // <- this and only this changed the filename
              })
          }
        }>
          Download QR Code
        </button>
```
